version: '3'
services:
  app:
    image: motion:latest
    tty: true
    ports:
      - "8001:8000"
    volumes:
      - ./backend:/backend
    env_file:
      - "./envs/dev.env"
    command:  "sh /scripts/dev.sh"
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    env_file:
      - "./envs/dev.env"
    ports:
      - "5555:5432"
    volumes:
      - "postgres_db:/var/lib/postgresql/data"

volumes:
  postgres_db:
