name: conda_motion

dependencies:
    - python = 3.11.0
    - pip = 23.0.1
    - psycopg2 = 2.9.3
    - pip:
          - django == 4.1.7
          - djangorestframework == 3.14.0
          - djangorestframework-simplejwt == 5.2.2
          - django-cors-headers == 3.14.0
          - drf-yasg == 1.21.5
          - flake8 == 6.0.0
          - gunicorn == 20.1.