# Generated by Django 4.1.7 on 2023-03-20 08:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_user_follower"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="follower",
            field=models.ManyToManyField(
                blank=True, related_name="following", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
