# Generated by Django 4.1.7 on 2023-03-30 08:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='receive_friend_request',
        ),
        migrations.RemoveField(
            model_name='user',
            name='sent_friend_request',
        ),
        migrations.AddField(
            model_name='user',
            name='sender_friend_request',
            field=models.ManyToManyField(blank=True, related_name='receiver_friend_requests', to=settings.AUTH_USER_MODEL),
        ),
    ]
