# Generated by Django 4.1.7 on 2023-03-27 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_user_follower"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="about_me",
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name="user",
            name="location",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="user",
            name="phone",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="user",
            name="tags",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
