# Generated by Django 4.1.7 on 2023-03-28 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration_profile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationprofile',
            name='password_reset',
            field=models.CharField(blank=True, max_length=5),
        ),
    ]
